include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.config.dart
    - lib/**.gr.dart

linter:
  rules:
    - prefer_single_quotes
    - sort_child_properties_last
    - sort_constructors_first
    - avoid_redundant_argument_values
