name: wishey
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^4.2.2
  freezed_annotation: ^2.1.0
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  json_annotation: ^4.6.0
  bloc: ^8.0.3
  injectable: ^1.5.3
  get_it: ^7.2.0
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  injectable_generator: ^1.5.4

flutter:
  uses-material-design: true