name: wishey
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^4.2.2
  provider: ^6.0.3
  collection: ^1.16.0
  http: ^0.13.5
  freezed_annotation: ^2.1.0
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  json_annotation: ^4.6.0
  bloc: ^8.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true